### PR TITLE
Add a 'change' trigger on input for second connected sortable

### PR DESCRIPTION
**Pull request by is7**
## Scope
This pull request includes a

- [x] Bug fix

## Changes
- Fixed bug: If SortableInput is used with at least 1 connected sortable, and item from SortableInput list was dragged off, input value changes, but 'change' event trigger doesn't fire.

### CODE REVIEW

**Comment by kartik-v** [comment]
Thanks can you submit a minified JS as well? You can minify the JS [from here](https://refresh-sf.com/)

**Comment by is7** [comment]
Done. Thanks for the link.

**Comment by is7** [comment]
Hi, is there something else required to accept this request?

**Comment by kartik-v** [comment]
Hi will check and update. Been busy lately

**Comment by kartik-v** [comment]
Thanks.

**Pull request merged**
